### ISSUE TITLE
How can I contact you for Leafie?

### ISSUE THREAD

**Issue by meow414** [ManBearPigg/FreeCodeCamp-Challenges#1]
First of all congrates  for your first real time web app. I want to know after creating 8 frontend projects on FCC, where did you learn rest of the things I mean for backend.  Which stack did you use for creating Leafie and how much time it took to make the final app.

**Comment by ManBearPigg** [comment]
Hello meow414. Please contact me at contact@leafie.io so that we may keep my repo clean, as this is not really an issue with the repo. I will answer any questions you have.
